format_version: 10
pipelines:
  My1stPipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      github-repo:
        git: https://github.com/appanp/spring-boot-h2-war-tomcat
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - Stage-1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          MvnBuildJob:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - package
                command: mvn
                run_if: passed
